name: api_client
description: Api client
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  dio: ^5.7.0
  http_parser: ^4.1.1
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.4.1


dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5
  very_good_analysis: ^7.0.0
