name: spase_logger
description: Logging tool
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
