name: spase_explorer
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^9.0.0
  flutter_native_splash: ^2.4.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.16
  intl: ^0.19.0
  formz: ^0.8.0
  gap: ^3.0.1
  go_router: ^14.6.2
  pretty_dio_logger: ^1.4.0
  spase_logger:
    path: packages/spase_logger

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true

flutter_gen:
  assets:
    enabled: true
  output: lib/core/design_system/generated/
  line_length: 80

  integrations:
    flutter_svg: true
