import 'package:flutter/material.dart';

abstract class SpaseColors {
  static const Color primary = Color(0xffc0c6db);
  static const Color onPrimary = Color(0xff293040);
  static const Color primaryContainer = Color(0xff111827);
  static const Color onPrimaryContainer = Color(0xff7a8194);
  static const Color secondary = Color(0xffa4c9ff);
  static const Color onSecondary = Color(0xff00315d);
  static const Color secondaryContainer = Color(0xff60a5fa);
  static const Color onSecondaryContainer = Color(0xff003a6b);
  static const Color tertiary = Color(0xffb5c6f4);
  static const Color onTertiary = Color(0xff1e2f55);
  static const Color tertiaryContainer = Color(0xff203157);
  static const Color onTertiaryContainer = Color(0xff899ac6);
  static const Color error = Color(0xffffb59a);
  static const Color onError = Color(0xff5a1b00);
  static const Color errorContainer = Color(0xffe76c39);
  static const Color onErrorContainer = Color(0xff3f1000);
  static const Color surface = Color(0xff131314);
  static const Color onSurface = Color(0xffe5e2e3);
  static const Color onSurfaceVariant = Color(0xffc6c6cd);
  static const Color outline = Color(0xff909097);
  static const Color outlineVariant = Color(0xff45474c);
  static const Color shadow = Color(0xff000000);
  static const Color scrim = Color(0xff000000);
  static const Color inverseSurface = Color(0xffe5e2e3);
  static const Color inversePrimary = Color(0xff575e70);
  static const Color primaryFixed = Color(0xffdce2f7);
  static const Color onPrimaryFixed = Color(0xff141b2b);
  static const Color primaryFixedDim = Color(0xffc0c6db);
  static const Color onPrimaryFixedVariant = Color(0xff404758);
  static const Color secondaryFixed = Color(0xffd4e3ff);
  static const Color onSecondaryFixed = Color(0xff001c39);
  static const Color secondaryFixedDim = Color(0xffa4c9ff);
  static const Color onSecondaryFixedVariant = Color(0xff004883);
  static const Color tertiaryFixed = Color(0xffd9e2ff);
  static const Color onTertiaryFixed = Color(0xff061a3f);
  static const Color tertiaryFixedDim = Color(0xffb5c6f4);
  static const Color onTertiaryFixedVariant = Color(0xff35466d);
  static const Color surfaceDim = Color(0xff131314);
  static const Color surfaceBright = Color(0xff39393a);
  static const Color surfaceContainerLowest = Color(0xff0e0e0f);
  static const Color surfaceContainerLow = Color(0xff1b1b1d);
  static const Color surfaceContainer = Color(0xff1f1f21);
  static const Color surfaceContainerHigh = Color(0xff2a2a2b);
  static const Color surfaceContainerHighest = Color(0xff353436);
}
